#!/bin/sh

cd ${1}
mkdir ${2}
cd ${2}
truffle init

npm init -y
npm install -E openzeppelin-solidity

cd migration
// Create JS file in migration
cd ..

cd contracts
#mv ... ${1}

// Create Sol file in contracts
